spring.application.name=English_quiz
server.port=8080
server.address=127.0.0.1
spring.datasource.url=jdbc:mysql://localhost:1024/english_quiz
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update